@startuml

skinparam defaultFontName Arial
skinparam roundcorner 20

package GameManagement{

    class "Character" {
        name
        health
        inventory
        level
        move()
        takeDamage()
        heal()
        pickUpItem()
        dropItem()
        displayStatus()


    }

}


